package com.test.lengyel.gui;

public enum FrameworkKindEnum {
	BUTTON, COMBOBOX, CHECKBOX, DROPDOWN, LABEL, LIST, PANEL, POPUP, RADIOBUTTON, SELECT, TABLE, TEXTFIELD, SELECTWITHTEXT, SELECTWITHOUTTEXT, INPUT
}
